name: Cordova Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # Set up Android SDK and Build Tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'

      # Install Android Build Tools
      cc

      # Set up Gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.6.5' # Specify a stable Gradle version compatible with Android builds

      # Install Cordova globally
      - name: Install Cordova
        run: npm install -g cordova

      # Find and unzip the project's zip file
      - name: Unzip project
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -name "*.zip" -type f)
          if [ -z "$ZIP_FILE" ]; then
            echo "No zip file found"
            exit 1
          fi
          unzip "$ZIP_FILE" -d project
          rm "$ZIP_FILE"

      # Navigate to unzipped project directory and run npm install
      - name: Install dependencies
        run: |
          cd project
          npm install

- name: Install Android Build Tools 892139890324
        run: |
          wget https://dl.google.com/android/repository/build-tools_r30.0.3-linux.zip
          unzip build-tools_r30.0.3-linux.zip -d /usr/local/lib/android/sdk/build-tools
          ls /usr/local/lib/android/sdk/build-tools/30.0.3
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}

      # Run npm build
      - name: Build project
        run: |
          cd project
          cordova build android --verbose -- --no-build-cache
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
